@startuml
!define Nube 0066ff/cce0ff
!define Control AB361D/CF7C57
!define TextoControl yellow
!define Servicio Yellow/Orange
!define cafca 339933/b3e6b3
!define repositorios bf40bf/ecc6ec
!define datos a3a3c2/e0e0eb
!define db 8cb1d9/e0e0eb
!define ColorFuente(clr) <font color=clr>

title Microservice with kafka and circuit breaker - Components Diagram

skinparam ArrowThickness 2
skinparam database {
    backgroundColor #db
}
skinparam cloud {
    backgroundColor #Nube
}

cloud Internet

database "Kafka - Zookeeper" {
    #datos [Topic: demo-microservices-cb-kafka-topic] as Topic
}

database MongoDb as MongoDb {
    #datos [Likes]
}

node "Microservice" {
    package "Controllers" {
      #Control [ColorFuente(TextoControl) Fail Simulator Controller] as FailController
      #Control [ColorFuente(TextoControl) Rock Band Likes Controller] as LikesController
      #Control [ColorFuente(TextoControl) Producer Controller] as ProducerController
    }

    package "Services" {
      #Servicio [Kafka Producer Service] as KafkaService
      #Servicio [Rock Band Likes Service] as RockBandService
      #Servicio [Fail Simulator Service] as FailService

    }

    package "Kafka" {
      #cafca [Consumer]
      #cafca [Producer]
    }

    node "Circuit Breaker" {
        package "Repositories" {
          #repositorios [Likes Repository] as LikesRepository
        }
    }
}

'Flujo de consumidor de kafka
Topic <-[#mediumPurple]- Consumer                 : "Listen vote events"
Consumer -[#mediumPurple]-> RockBandService       : "Calls to"
RockBandService -[#mediumPurple]-> LikesRepository: "Update votes"

'Flujo de productor de kafka
Internet --> ProducerController     : "Request to \ngenerate \nrock band\nvotes"
ProducerController --> KafkaService : "Mimic fan's votes"
KafkaService --> Producer           : "Produces vote events"
Producer --> Topic                  : "Injects \nvote events"

'Flujo de consulta de votos
Internet -[#blue]-> LikesController       : "Get\nvotes"
LikesController -[#blue]-> RockBandService: "Get\nvotes"
RockBandService -[#blue]-> LikesRepository: "Get\nvotes"

'Flujo de simulación de fallas
Internet -[#green]-> FailController    : "Mimic delays\nin MongoDb"
FailController -[#green]-> FailService : "Set delays\nin MongoDb"
FailService -[#green]-> LikesRepository: "Delays repository execution"
LikesRepository -[#green]-> Likes      : "Access to likes"

@enduml