version: '3'
services:
  app:
    image: docker.io/library/demo-ms-cb-kafka:0.0.1-SNAPSHOT
    container_name: app
    ports:
      - "8081:8080"
    depends_on:
      - mongodb
      - zookeeper
      - kafka
      - prometheus
      - grafana
  mongodb:
    image: mongo:4.0.4
    container_name: mongodb
    ports:
      - 27017-27019:27017-27019
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: ./docker/kafka-docker
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.102
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "8080:8080"
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - ./docker/grafana/grafana.env
    volumes:
      - ./docker/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./docker/grafana/provisioning/:/etc/grafana/provisioning/