spring:
  application:
    name: demo-microservices-cb-kafka
  data:
    mongodb:
      uri: mongodb://mongodb:27017/demo-ms-cb-kafka
#      uri: mongodb://root:root@localhost:27017/demo-ms-cb-kafka

  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers:
            - kafka:9092
        streams:
          binder:
            configuration:
              commit:
                interval:
                  ms: 1000
      bindings:
        input:
          binder: kafka
          destination: demo-ms-cb-kafka-topic
          group: input-group-1
          content-type: text/plain
        output:
          binder: kafka
          destination: demo-ms-cb-kafka-topic
          group: output-group-1
          content-type: text/plain
          producer:
            partitionCount: 3

logging:
  level:
    root: INFO